CREATE TABLE `jv_partner_prospects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`organizationName` varchar(255) NOT NULL,
	`partnerType` varchar(128) NOT NULL,
	`region` varchar(128) NOT NULL,
	`city` varchar(128),
	`submarket` varchar(255),
	`website` text,
	`contactName` varchar(255),
	`contactTitle` varchar(255),
	`email` varchar(320),
	`phone` varchar(64),
	`linkedInUrl` text,
	`assetFocus` text,
	`developmentFocus` text,
	`texasMarkets` text,
	`typicalProjectScale` varchar(255),
	`jvExperience` text,
	`landContributionPotential` varchar(32) NOT NULL DEFAULT 'Unknown',
	`capitalContributionPotential` varchar(32) NOT NULL DEFAULT 'Unknown',
	`developmentContributionPotential` varchar(32) NOT NULL DEFAULT 'Unknown',
	`facilityContributionPotential` varchar(32) NOT NULL DEFAULT 'Unknown',
	`strategicFit` varchar(32) NOT NULL DEFAULT 'Low',
	`priority` enum('A','B','C') NOT NULL DEFAULT 'C',
	`priorityRationale` text,
	`ceRelevance` text,
	`jvThesis` text,
	`source` varchar(255) NOT NULL,
	`sourceUrl` text NOT NULL,
	`researchDate` timestamp NOT NULL,
	`status` enum('prospect','research','qualified','converted','passed') NOT NULL DEFAULT 'prospect',
	`nextAction` varchar(500),
	`convertedCapitalOpportunityId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jv_partner_prospects_id` PRIMARY KEY(`id`),
	CONSTRAINT `jv_prospect_owner_organization_unique` UNIQUE(`ownerId`,`organizationName`)
);
