CREATE TABLE `grant_award_disbursements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`awardId` int NOT NULL,
	`receivedAmount` int NOT NULL,
	`receivedAt` timestamp NOT NULL,
	`reference` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grant_award_disbursements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `grant_compliance_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`awardId` int NOT NULL,
	`requirementType` enum('reporting','match','milestone','eligible_cost','documentation','workforce','job_creation','performance','closeout','other') NOT NULL,
	`requirementDescription` text NOT NULL,
	`dueAt` timestamp,
	`ownerName` varchar(255),
	`status` enum('not_started','in_progress','submitted','complete','overdue','waived') NOT NULL DEFAULT 'not_started',
	`completedAt` timestamp,
	`sourceReference` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grant_compliance_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `grant_funding_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`opportunityId` int NOT NULL,
	`applicationStatus` enum('not_started','drafting','submitted','under_review','awarded','declined','withdrawn','closed') NOT NULL DEFAULT 'not_started',
	`requestedAmount` int,
	`matchAmount` int,
	`submissionAt` timestamp,
	`decisionAt` timestamp,
	`applicationOwner` varchar(255),
	`submissionReference` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grant_funding_applications_id` PRIMARY KEY(`id`),
	CONSTRAINT `grant_application_owner_opportunity_unique` UNIQUE(`ownerId`,`opportunityId`)
);
--> statement-breakpoint
CREATE TABLE `grant_funding_awards` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`applicationId` int NOT NULL,
	`capitalOpportunityId` int,
	`awardStatus` enum('pending','awarded','declined','rescinded','closed') NOT NULL DEFAULT 'pending',
	`awardAmount` int,
	`awardDate` timestamp,
	`awardReference` varchar(255),
	`matchAmount` int,
	`awardDataState` enum('actual','projected','estimated','missing') NOT NULL DEFAULT 'missing',
	`reportingRequirementSummary` text,
	`closeoutDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grant_funding_awards_id` PRIMARY KEY(`id`),
	CONSTRAINT `grant_award_owner_application_unique` UNIQUE(`ownerId`,`applicationId`)
);
--> statement-breakpoint
CREATE TABLE `grant_funding_opportunities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`programId` int NOT NULL,
	`capitalOpportunityId` int,
	`opportunityName` varchar(500) NOT NULL,
	`linkedProject` varchar(255),
	`linkedFacility` varchar(255),
	`linkedEquipment` varchar(500),
	`linkedWorkforceInitiative` varchar(500),
	`linkedTechnology` varchar(500),
	`ceStrategicThesis` text,
	`requestedAmount` int,
	`proposedMatchAmount` int,
	`ownerName` varchar(255),
	`status` enum('draft','qualified','passed','application_started','submitted','under_review','awarded','declined','closed') NOT NULL DEFAULT 'draft',
	`nextAction` varchar(500),
	`nextActionDueAt` timestamp,
	`targetSubmissionAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grant_funding_opportunities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `grant_funding_programs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`programName` varchar(500) NOT NULL,
	`sponsor` varchar(255) NOT NULL,
	`mechanismType` enum('grant','tax_credit','tax_abatement','rebate','loan','forgivable_loan','workforce_incentive','infrastructure_incentive','economic_development_incentive','research_funding','technical_assistance','other') NOT NULL,
	`governmentLevel` enum('federal','state','regional','local','utility','strategic','other') NOT NULL,
	`texasRegion` varchar(255),
	`industryFocus` text,
	`programDescription` text,
	`programUrl` text NOT NULL,
	`sourceUrl` text NOT NULL,
	`sourceLabel` varchar(255) NOT NULL,
	`researchDate` timestamp NOT NULL,
	`applicationWindow` enum('open','upcoming','closed','unknown') NOT NULL DEFAULT 'unknown',
	`applicationOpenAt` timestamp,
	`applicationDeadline` timestamp,
	`expectedAwardAt` timestamp,
	`awardMinimum` int,
	`awardMaximum` int,
	`typicalAward` int,
	`matchRequired` enum('yes','no','unknown') NOT NULL DEFAULT 'unknown',
	`matchBps` int,
	`fundingBps` int,
	`eligibleExpenses` text,
	`companyEligibility` text,
	`projectEligibility` text,
	`geographicEligibility` text,
	`industryEligibility` text,
	`requiredCertifications` text,
	`otherRequirements` text,
	`ceEligibilityEvidence` boolean,
	`projectEligibilityEvidence` boolean,
	`geographicEligibilityEvidence` boolean,
	`manufacturingRelevanceEvidence` boolean,
	`roboticsAutomationRelevanceEvidence` boolean,
	`activeWindowEvidence` boolean,
	`strategicFitEvidence` boolean,
	`priority` enum('A','B','C') NOT NULL DEFAULT 'C',
	`priorityRationale` text,
	`ceRelevance` text,
	`status` enum('research','qualified','passed') NOT NULL DEFAULT 'research',
	`nextAction` varchar(500),
	`nextActionDueAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grant_funding_programs_id` PRIMARY KEY(`id`),
	CONSTRAINT `grant_program_owner_name_unique` UNIQUE(`ownerId`,`programName`)
);
