CREATE TABLE `project_planning_wbs_lines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`internalProjectId` int NOT NULL,
	`projectionScenarioId` int NOT NULL,
	`wbsCode` varchar(32) NOT NULL,
	`description` varchar(500) NOT NULL,
	`costCategory` varchar(128) NOT NULL,
	`phase` varchar(128) NOT NULL,
	`buildingApplicability` varchar(255) NOT NULL,
	`quantity` int NOT NULL,
	`quantityUnit` varchar(64) NOT NULL,
	`unitCost` int NOT NULL,
	`allocatedAmount` int NOT NULL,
	`dataState` enum('actual','projected','estimated','missing') NOT NULL DEFAULT 'estimated',
	`sourceClassification` enum('historical_control','reverse_engineered_allocation','derived_quantity','source_document') NOT NULL DEFAULT 'reverse_engineered_allocation',
	`sourceReference` varchar(500),
	`effectiveAt` timestamp,
	`ownerName` varchar(255),
	`notes` text,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_planning_wbs_lines_id` PRIMARY KEY(`id`),
	CONSTRAINT `project_planning_wbs_owner_scenario_code_unique` UNIQUE(`ownerId`,`projectionScenarioId`,`wbsCode`)
);
