import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { getSessionCookieOptions } from "./_core/cookies";
import { COOKIE_NAME } from "../shared/const";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, protectedProcedure, router } from "./_core/trpc";
import { addOutreachEvent, createInvestorContact, getGmailConnection, getInvestorContact, listInvestorContacts, updateInvestorContact, listInvestorEvents, listCampaigns, createCampaign, updateCampaign, deleteCampaign, listFundraisingDocuments, createFundraisingDocument, updateFundraisingDocument, listCampaignDocumentLinks, linkDocumentToCampaign, unlinkDocumentFromCampaign, deleteFundraisingDocument, listInvestorDocumentLinks, linkDocumentToInvestor, unlinkDocumentFromInvestor, listTasks, createTask, updateTask, listMeetings, createMeeting, getFundraisingAnalytics, createInvestorResearchProposal, getInvestorResearchProposal, listInvestorResearchProposals, listInvestorResearchSources, updateInvestorResearchProposalStatus, ensureCapitalBuckets, listCapitalBuckets, updateCapitalBucket, listCapitalOpportunities, createCapitalOpportunity, updateCapitalOpportunity, bootstrapEquityCapitalOpportunities, listCapitalOpportunityDocumentLinks, linkDocumentToCapitalOpportunity, unlinkDocumentFromCapitalOpportunity, getFacilityJvDetail, upsertFacilityJvDetail, getEquipmentFinanceDetail, listEquipmentFinanceDetails, upsertEquipmentFinanceDetail, getGrantDetail, upsertGrantDetail, listGrantFundingPrograms, createGrantFundingProgram, updateGrantFundingProgram, importTexasGrantsIncentivesMasterUniverse, listGrantFundingOpportunities, createGrantFundingOpportunity, updateGrantFundingOpportunity, listGrantFundingApplications, createGrantFundingApplication, updateGrantFundingApplication, listGrantFundingAwards, saveGrantFundingAward, listGrantAwardDisbursements, createGrantAwardDisbursement, listGrantComplianceItems, createGrantComplianceItem, updateGrantComplianceItem, listJvPartnerProspects, getJvPartnerProspect, createJvPartnerProspect, updateJvPartnerProspect, convertJvProspectToCapitalOpportunity, importTexasJvMasterUniverse, importTexasEquipmentRentalMasterUniverse, createEquipmentActiveRental, createEquipmentRentalQuote, createEquipmentRentalRequirement, createEquipmentRentalVendor, getEquipmentRentalVendor, listEquipmentActiveRentals, listEquipmentRentalQuotes, listEquipmentRentalRequirements, listEquipmentRentalVendors, updateEquipmentActiveRental, updateEquipmentRentalQuote, updateEquipmentRentalRequirement, updateEquipmentRentalVendor } from "./db";
import { sendGmailMessage } from "./gmail";
import { canSendFromGmailStatus, canSendToContactStatus } from "../shared/outreach";
import { generateInvestorDraft, classifyInvestor, summarizeInvestorHistory } from "./ai";
import { fetchPublicResearchSources, generateInvestorResearchProposal } from "./investorResearch";
import { storageGetSignedUrl, storagePut } from "./storage";
import { scoreJvProspect } from "../shared/jvProspects";
import { scoreEquipmentRentalVendor } from "../shared/equipmentOperations";
import { loadTexasJvMasterUniverse } from "./texasJvMasterUniverse";
import { loadTexasGrantsIncentivesMasterUniverse } from "./texasGrantsIncentivesMasterUniverse";
import { createRoiCapitalSource, createRoiJvContributionComponent, createRoiProject, createRoiScenario, getCrossDomainRoiSnapshot, listRoiCapitalSources, listRoiCashFlows, listRoiJvContributionComponents, listRoiProjects, listRoiReturnDetails, listRoiScenarios, updateRoiCapitalSource, updateRoiJvContributionComponent, updateRoiProject, updateRoiScenario, upsertRoiCashFlow, upsertRoiEquipmentReturnDetail, upsertRoiEquityReturnDetail, upsertRoiGrantReturnDetail, upsertRoiJvReturnDetail } from "./roi";
import { createInternalProject, getInternalProjectCapitalStack, linkDocumentToInternalProject, listInternalProjectCapitalNeeds, listInternalProjectCapitalNeedStrategies, listInternalProjectDocumentLinks, listInternalProjects, saveInternalProjectCapitalNeed, seedInitialInternalProjects, unlinkDocumentFromInternalProject, updateInternalProject } from "./internalProjects";
import { getProjectEconomicsModelForProject, getProjectEconomicsReadiness, initializeChappellProjectEconomicsModel, initializeProjectEconomicsModel, linkDocumentToProjectEconomicsInput, listProjectEconomicsInputDocuments, listProjectEconomicsInputs, listProjectEconomicsMonthlyItems, saveProjectEconomicsInput, saveProjectEconomicsMonthlyItem, unlinkDocumentFromProjectEconomicsInput } from "./projectEconomics";
import { createProjectionScenario, ensureProjectionScenarioShells, getFinancialOsPortfolioSnapshot, getHistoricalPlanningBudgetComparison, getProjectionSnapshot, listProjectionAssumptions, listProjectionMonthlyLines, listProjectionScenarios, saveProjectionAssumption, saveProjectionMonthlyLine, updateProjectionScenario } from "./projections";
import { getProjectPlanningWbsSummary, listProjectPlanningWbsLines, seedCedarwoodHistoricalPlanningWbs } from "./projectPlanningWbs";
import { getCedarwoodScheduleFinancingSnapshot, getProjectPlanningFinancingTerms, listProjectPlanningScheduleMonths, saveProjectPlanningFinancingTerms, saveProjectPlanningScheduleMonths } from "./projectPlanningScheduleFinancing";
import { cloneCedarwoodScenario, getCedarwoodScenarioMatrix, listCedarwoodScenarioUnitMix, saveCedarwoodScenarioUnitMix } from "./cedarwoodScenarioMatrix";

const contactInput = z.object({
  firmName: z.string().min(1),
  contactName: z.string().optional(),
  email: z.string().email(),
  type: z.string().default("VC"),
  fitScore: z.number().int().min(0).max(10).optional(),
  thesis: z.string().optional(),
  contactUrl: z.string().optional(),
});

const campaignInput = z.object({ name: z.string().min(1), description: z.string().optional(), groupName: z.string().min(1).max(128).default("Ungrouped"), sortOrder: z.number().int().optional(), funnelStage: z.string().default("1,000"), targetCount: z.number().int().positive().optional(), status: z.enum(["planning", "active", "paused", "completed"]).default("planning") });
const taskInput = z.object({ title: z.string().min(1), description: z.string().optional(), investorId: z.number().int().optional(), campaignId: z.number().int().optional(), dueAt: z.coerce.date().optional(), status: z.enum(["open", "in_progress", "done", "snoozed"]).default("open") });
const meetingInput = z.object({ title: z.string().min(1), investorId: z.number().int().optional(), campaignId: z.number().int().optional(), scheduledAt: z.coerce.date(), status: z.enum(["scheduled", "completed", "cancelled"]).default("scheduled"), notes: z.string().optional() });
const capitalPathInput = z.enum(["equity", "facility_jv", "equipment_finance", "grants"]);
const capitalStageInput = z.enum(["identified", "researching", "outreach", "meeting", "diligence", "term_sheet", "committed", "passed"]);
const capitalOpportunityInput = z.object({ capitalPath: capitalPathInput, organizationName: z.string().min(1).max(255), opportunityName: z.string().max(255).optional(), internalProjectId: z.number().int().optional(), projectName: z.string().max(255).optional(), facilityName: z.string().max(255).optional(), contactName: z.string().max(255).optional(), contactRole: z.string().max(255).optional(), decisionMaker: z.string().max(255).optional(), relationshipStrength: z.string().max(128).optional(), email: z.string().email().optional(), contactUrl: z.string().url().optional(), stage: capitalStageInput.default("identified"), requestedAmount: z.number().int().min(0).optional(), committedAmount: z.number().int().min(0).default(0), fundedAmount: z.number().int().min(0).default(0), probability: z.number().int().min(0).max(100).default(0), linkedInvestorId: z.number().int().optional(), campaignId: z.number().int().optional(), source: z.string().max(255).optional(), termsNotes: z.string().optional(), nextAction: z.string().max(500).optional(), nextActionDueAt: z.coerce.date().optional(), targetCloseAt: z.coerce.date().optional(), firstContactAt: z.coerce.date().optional(), lastContactAt: z.coerce.date().optional() });
const facilityJvDetailInput = z.object({ capitalOpportunityId: z.number().int(), partnerRole: z.string().max(255).optional(), facilityContribution: z.number().int().min(0).optional(), ceContribution: z.number().int().min(0).optional(), facilityDescription: z.string().optional(), jvType: z.string().max(128).optional(), ownershipStructure: z.string().optional(), proposedEconomics: z.string().optional(), proposedTerms: z.string().optional(), operatorResponsibilities: z.string().optional(), facilityLifecycle: z.string().max(128).optional(), facilityPurpose: z.string().optional(), capacity: z.string().max(255).optional(), equipmentIncluded: z.string().optional(), expansionPhase: z.string().max(128).optional(), diligenceStatus: z.string().max(128).optional(), financialsReceived: z.boolean().optional(), termSheetReceived: z.boolean().optional(), loiReceived: z.boolean().optional(), legalReviewed: z.boolean().optional(), siteDocumentationReceived: z.boolean().optional(), corporateDocumentationReceived: z.boolean().optional(), otherDiligenceRequirements: z.string().optional() });
const equipmentFinanceDetailInput = z.object({ capitalOpportunityId: z.number().int(), equipmentAsset: z.string().max(500).optional(), equipmentCategory: z.string().max(255).optional(), manufacturer: z.string().max(255).optional(), model: z.string().max(255).optional(), equipmentCondition: z.string().max(64).optional(), vendor: z.string().max(255).optional(), equipmentCost: z.number().int().min(0).optional(), quantity: z.number().int().positive().optional(), productionUse: z.string().optional(), expectedStartDate: z.coerce.date().optional(), usefulLifeMonths: z.number().int().positive().optional(), financingAmount: z.number().int().min(0).optional(), downPayment: z.number().int().min(0).optional(), termMonths: z.number().int().positive().optional(), rateBps: z.number().int().min(0).optional(), monthlyPayment: z.number().int().min(0).optional(), residualBuyout: z.number().int().min(0).optional(), structure: z.enum(["loan", "lease", "other"]).optional(), financingProgram: z.string().max(255).optional(), financierContactRole: z.string().max(255).optional(), collateral: z.string().optional(), approvalStatus: z.string().max(128).optional(), diligenceStatus: z.string().max(128).optional(), termsState: z.enum(["missing", "estimated", "quoted", "approved", "actual"]).default("missing"), expectedUtilizationBps: z.number().int().min(0).max(10000).optional(), incrementalProduction: z.string().optional(), incrementalRevenue: z.number().int().min(0).optional(), operatingSavings: z.number().int().min(0).optional(), economicsPeriodMonths: z.number().int().positive().optional(), financingCost: z.number().int().min(0).optional(), fundingDate: z.coerce.date().optional() });
const equipmentRentalVendorInput = z.object({ organizationName: z.string().min(1).max(255), vendorType: z.string().min(1).max(128), equipmentCategories: z.string().optional(), region: z.string().min(1).max(128), city: z.string().max(128).optional(), serviceArea: z.string().optional(), website: z.string().url().optional(), contactName: z.string().max(255).optional(), contactTitle: z.string().max(255).optional(), email: z.string().email().optional(), phone: z.string().max(64).optional(), equipmentFocus: z.string().optional(), deliveryAvailable: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), pickupAvailable: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), operatorServices: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), shortTermRental: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), longTermRental: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), newUsedSales: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), serviceMaintenance: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), strategicFit: z.enum(["High", "Medium", "Low"]).default("Low"), ceRelevance: z.string().optional(), source: z.string().min(1).max(255), sourceUrl: z.string().url(), researchDate: z.coerce.date(), status: z.enum(["prospect", "research", "qualified", "passed"]).default("prospect"), nextAction: z.string().max(500).optional(), nextActionDueAt: z.coerce.date().optional() });
const equipmentRentalRequirementInput = z.object({ projectId: z.number().int().optional(), projectName: z.string().max(255).optional(), facilityName: z.string().max(255).optional(), equipmentName: z.string().min(1).max(500), equipmentCategory: z.string().max(255).optional(), quantity: z.number().int().positive().default(1), productionUse: z.string().optional(), requiredStartDate: z.coerce.date().optional(), expectedEndDate: z.coerce.date().optional(), expectedUtilizationBps: z.number().int().min(0).max(10000).optional(), status: z.enum(["draft", "sourcing", "quoting", "selected", "active", "completed", "cancelled"]).default("draft"), nextAction: z.string().max(500).optional(), nextActionDueAt: z.coerce.date().optional(), notes: z.string().optional() });
const planningPhaseInput = z.enum(["predevelopment", "design_entitlement", "construction", "building_completion", "lease_up_stabilization", "commissioning", "operating_ramp", "stabilized_operations"]);
const cedarwoodPlanningScheduleInput = z.object({ scenarioId: z.number().int(), sourceReference: z.string().min(1).max(500), effectiveAt: z.coerce.date().nullable().optional(), ownerName: z.string().min(1).max(255), dataState: z.enum(["projected", "estimated"]), notes: z.string().max(4000).optional(), rows: z.array(z.object({ monthIndex: z.number().int().min(1).max(36), phase: planningPhaseInput, constructionSpendBps: z.number().int().min(0).max(10000).nullable(), occupancyBps: z.number().int().min(0).max(10000).nullable() })).min(1).max(36) });
const cedarwoodPlanningFinancingInput = z.object({ scenarioId: z.number().int(), loanAmount: z.number().int().positive(), annualInterestRateBps: z.number().int().min(0).max(100000), financingFeeBps: z.number().int().min(0).max(10000).optional(), termMonths: z.number().int().positive().max(600), amortizationMonths: z.number().int().positive().max(600), interestOnlyMonths: z.number().int().min(0).max(600), closingMonth: z.number().int().min(1).max(36), sourceReference: z.string().min(1).max(500), effectiveAt: z.coerce.date().nullable().optional(), ownerName: z.string().min(1).max(255), dataState: z.enum(["projected", "estimated"]), notes: z.string().max(4000).optional() });
const cedarwoodScenarioUnitMixInput = z.object({ scenarioId: z.number().int(), unitType: z.string().min(1).max(128), unitCount: z.number().int().positive(), averageSqFt: z.number().int().positive().nullable().optional(), monthlyRent: z.number().int().positive().nullable().optional(), sourceReference: z.string().min(1).max(500), effectiveAt: z.coerce.date().nullable().optional(), ownerName: z.string().min(1).max(255), dataState: z.enum(["projected", "estimated"]), notes: z.string().max(4000).optional() });
const cedarwoodScenarioCloneInput = z.object({ sourceScenarioId: z.number().int(), scenarioName: z.string().min(1).max(255) });
const equipmentRentalQuoteInput = z.object({ requirementId: z.number().int(), vendorId: z.number().int(), quoteStatus: z.enum(["requested", "received", "declined", "expired", "selected"]).default("requested"), currency: z.literal("USD").default("USD"), rateUnit: z.enum(["daily", "weekly", "monthly", "project"]).default("monthly"), quotedRate: z.number().int().min(0).optional(), deliveryFee: z.number().int().min(0).optional(), pickupFee: z.number().int().min(0).optional(), estimatedTotal: z.number().int().min(0).optional(), quoteValidUntil: z.coerce.date().optional(), availabilityNote: z.string().optional(), serviceNote: z.string().optional(), termsNotes: z.string().optional() });
const equipmentActiveRentalInput = z.object({ requirementId: z.number().int(), quoteId: z.number().int(), vendorId: z.number().int(), status: z.enum(["scheduled", "active", "return_due", "returned", "cancelled"]).default("scheduled"), scheduledStartDate: z.coerce.date().optional(), scheduledEndDate: z.coerce.date().optional(), actualStartDate: z.coerce.date().optional(), actualReturnDate: z.coerce.date().optional(), actualRentalCost: z.number().int().min(0).optional(), actualDeliveryFee: z.number().int().min(0).optional(), actualPickupFee: z.number().int().min(0).optional(), servicePerformanceNote: z.string().optional(), returnConditionNote: z.string().optional() });
const grantDetailInput = z.object({ capitalOpportunityId: z.number().int(), program: z.string().max(500).optional(), agency: z.string().max(255).optional(), eligibility: z.string().optional(), awardCeiling: z.number().int().min(0).optional(), matchRequirement: z.string().optional(), applicationDeadline: z.coerce.date().optional(), eligibleCosts: z.string().optional(), applicationStatus: z.string().max(128).optional(), awardStatus: z.string().max(128).optional(), reportingRequirements: z.string().optional() });
const grantMechanismInput = z.enum(["grant", "tax_credit", "tax_abatement", "rebate", "loan", "forgivable_loan", "workforce_incentive", "infrastructure_incentive", "economic_development_incentive", "research_funding", "technical_assistance", "other"]);
const grantFundingProgramInput = z.object({ programName: z.string().min(1).max(500), sponsor: z.string().min(1).max(255), mechanismType: grantMechanismInput, governmentLevel: z.enum(["federal", "state", "regional", "local", "utility", "strategic", "other"]), texasRegion: z.string().max(255).optional(), industryFocus: z.string().optional(), programDescription: z.string().optional(), programUrl: z.string().url(), sourceUrl: z.string().url(), sourceLabel: z.string().min(1).max(255), researchDate: z.coerce.date(), applicationWindow: z.enum(["open", "upcoming", "closed", "unknown"]).default("unknown"), applicationOpenAt: z.coerce.date().optional(), applicationDeadline: z.coerce.date().optional(), expectedAwardAt: z.coerce.date().optional(), awardMinimum: z.number().int().min(0).optional(), awardMaximum: z.number().int().min(0).optional(), typicalAward: z.number().int().min(0).optional(), matchRequired: z.enum(["yes", "no", "unknown"]).default("unknown"), matchBps: z.number().int().min(0).max(10000).optional(), fundingBps: z.number().int().min(0).max(10000).optional(), eligibleExpenses: z.string().optional(), companyEligibility: z.string().optional(), projectEligibility: z.string().optional(), geographicEligibility: z.string().optional(), industryEligibility: z.string().optional(), requiredCertifications: z.string().optional(), otherRequirements: z.string().optional(), ceEligibilityEvidence: z.boolean().nullable().optional(), projectEligibilityEvidence: z.boolean().nullable().optional(), geographicEligibilityEvidence: z.boolean().nullable().optional(), manufacturingRelevanceEvidence: z.boolean().nullable().optional(), roboticsAutomationRelevanceEvidence: z.boolean().nullable().optional(), activeWindowEvidence: z.boolean().nullable().optional(), strategicFitEvidence: z.boolean().nullable().optional(), ceRelevance: z.string().optional(), status: z.enum(["research", "qualified", "passed"]).default("research"), nextAction: z.string().max(500).optional(), nextActionDueAt: z.coerce.date().optional(), notes: z.string().optional() });
const grantFundingOpportunityInput = z.object({ programId: z.number().int(), opportunityName: z.string().min(1).max(500), linkedProject: z.string().max(255).optional(), linkedFacility: z.string().max(255).optional(), linkedEquipment: z.string().max(500).optional(), linkedWorkforceInitiative: z.string().max(500).optional(), linkedTechnology: z.string().max(500).optional(), ceStrategicThesis: z.string().optional(), requestedAmount: z.number().int().min(0).optional(), proposedMatchAmount: z.number().int().min(0).optional(), ownerName: z.string().max(255).optional(), status: z.enum(["draft", "qualified", "passed", "application_started", "submitted", "under_review", "awarded", "declined", "closed"]).default("draft"), nextAction: z.string().max(500).optional(), nextActionDueAt: z.coerce.date().optional(), targetSubmissionAt: z.coerce.date().optional(), notes: z.string().optional() });
const grantFundingApplicationInput = z.object({ opportunityId: z.number().int(), applicationStatus: z.enum(["not_started", "drafting", "submitted", "under_review", "awarded", "declined", "withdrawn", "closed"]).default("not_started"), requestedAmount: z.number().int().min(0).optional(), matchAmount: z.number().int().min(0).optional(), submissionAt: z.coerce.date().optional(), decisionAt: z.coerce.date().optional(), applicationOwner: z.string().max(255).optional(), submissionReference: z.string().max(255).optional(), notes: z.string().optional() });
const grantFundingAwardInput = z.object({ applicationId: z.number().int(), awardStatus: z.enum(["pending", "awarded", "declined", "rescinded", "closed"]).default("pending"), awardAmount: z.number().int().min(0).optional(), awardDate: z.coerce.date().optional(), awardReference: z.string().max(255).optional(), matchAmount: z.number().int().min(0).optional(), awardDataState: z.enum(["actual", "projected", "estimated", "missing"]).default("missing"), reportingRequirementSummary: z.string().optional(), closeoutDate: z.coerce.date().optional(), notes: z.string().optional() });
const grantAwardDisbursementInput = z.object({ awardId: z.number().int(), receivedAmount: z.number().int().positive(), receivedAt: z.coerce.date(), reference: z.string().max(255).optional(), notes: z.string().optional() });
const grantComplianceItemInput = z.object({ awardId: z.number().int(), requirementType: z.enum(["reporting", "match", "milestone", "eligible_cost", "documentation", "workforce", "job_creation", "performance", "closeout", "other"]), requirementDescription: z.string().min(1), dueAt: z.coerce.date().optional(), ownerName: z.string().max(255).optional(), status: z.enum(["not_started", "in_progress", "submitted", "complete", "overdue", "waived"]).default("not_started"), completedAt: z.coerce.date().optional(), sourceReference: z.string().optional(), notes: z.string().optional() });
const jvProspectInput = z.object({ organizationName: z.string().min(1).max(255), partnerType: z.string().min(1).max(128), region: z.string().min(1).max(128), city: z.string().max(128).optional(), submarket: z.string().max(255).optional(), website: z.string().url().optional(), contactName: z.string().max(255).optional(), contactTitle: z.string().max(255).optional(), email: z.string().email().optional(), phone: z.string().max(64).optional(), linkedInUrl: z.string().url().optional(), assetFocus: z.string().optional(), developmentFocus: z.string().optional(), texasMarkets: z.string().optional(), typicalProjectScale: z.string().max(255).optional(), jvExperience: z.string().optional(), landContributionPotential: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), capitalContributionPotential: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), developmentContributionPotential: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), facilityContributionPotential: z.enum(["Yes", "No", "Unknown"]).default("Unknown"), strategicFit: z.enum(["High", "Medium", "Low"]).default("Low"), priority: z.enum(["A", "B", "C"]).default("C"), priorityRationale: z.string().optional(), ceRelevance: z.string().optional(), jvThesis: z.string().optional(), source: z.string().min(1).max(255), sourceUrl: z.string().url(), researchDate: z.coerce.date(), status: z.enum(["prospect", "research", "qualified", "converted", "passed"]).default("prospect"), indicativeCapitalAmount: z.number().int().min(0).optional(), nextAction: z.string().max(500).optional(), nextActionDueAt: z.coerce.date().optional() });
const roiProjectInput = z.object({ projectName: z.string().min(1).max(255), projectStatus: z.enum(["planning", "active", "completed", "paused"]).default("planning"), description: z.string().optional(), capitalRequirement: z.number().int().min(0).optional(), capitalDeployedActual: z.number().int().min(0).optional(), projectedRevenue: z.number().int().min(0).optional(), actualRevenue: z.number().int().min(0).optional(), projectedCost: z.number().int().min(0).optional(), actualCost: z.number().int().min(0).optional(), projectionPeriodMonths: z.number().int().positive().optional(), actualPeriodMonths: z.number().int().positive().optional() });
const roiCapitalSourceInput = z.object({ projectId: z.number().int(), capitalPath: capitalPathInput, capitalOpportunityId: z.number().int().optional(), sourceName: z.string().min(1).max(255), capitalCommitted: z.number().int().min(0).default(0), capitalDeployed: z.number().int().min(0).default(0), costOfCapital: z.number().int().min(0).optional(), expectedCeReturn: z.number().int().min(0).optional(), actualCeReturn: z.number().int().min(0).optional(), notes: z.string().optional() });
const roiCashFlowInput = z.object({ projectId: z.number().int(), monthIndex: z.number().int().min(0), amount: z.number().int(), flowType: z.enum(["forecast", "actual"]).default("forecast"), notes: z.string().optional() });
const roiScenarioInput = z.object({ projectId: z.number().int(), scenarioName: z.string().min(1).max(128), scenarioType: z.enum(["base", "upside", "downside", "custom"]).default("custom"), revenue: z.number().int().min(0).optional(), cost: z.number().int().min(0).optional(), capitalRequired: z.number().int().min(0).optional(), periodMonths: z.number().int().positive().optional(), notes: z.string().optional() });
const roiContributionComponentInput = z.object({ capitalSourceId: z.number().int(), contributor: z.enum(["ce", "partner"]), componentType: z.enum(["cash", "technology", "equipment", "operations", "ip_systems", "land", "facility", "financing", "development_services", "other"]), amount: z.number().int().min(0), notes: z.string().optional() });
const roiEquityReturnInput = z.object({ capitalSourceId: z.number().int(), dilutionBps: z.number().int().min(0).max(10000).optional(), investorMultipleBps: z.number().int().min(0).optional(), expectedInvestorReturn: z.number().int().min(0).optional() });
const roiJvReturnInput = z.object({ capitalSourceId: z.number().int(), ceContribution: z.number().int().min(0).optional(), partnerContribution: z.number().int().min(0).optional(), ceOwnershipBps: z.number().int().min(0).max(10000).optional(), expectedDistributions: z.number().int().min(0).optional(), actualDistributions: z.number().int().min(0).optional() });
const roiEquipmentReturnInput = z.object({ capitalSourceId: z.number().int(), equipmentCost: z.number().int().min(0).optional(), financingCost: z.number().int().min(0).optional(), annualProductivityValue: z.number().int().min(0).optional(), incrementalRevenue: z.number().int().min(0).optional() });
const roiGrantReturnInput = z.object({ capitalSourceId: z.number().int(), awardAmount: z.number().int().min(0).optional(), matchAmount: z.number().int().min(0).optional(), administrativeCost: z.number().int().min(0).optional(), projectValueEnabled: z.number().int().min(0).optional() });
const dataStateInput = z.enum(["actual", "projected", "estimated", "missing"]);
const internalProjectInput = z.object({ projectName: z.string().min(1).max(255), projectCode: z.string().min(1).max(128).optional(), projectType: z.string().max(128).optional(), location: z.string().max(255).optional(), projectStatus: z.enum(["planning", "active", "on_hold", "completed", "cancelled"]).default("planning"), developmentStage: z.enum(["concept", "predevelopment", "development", "construction", "commissioning", "operations", "completed"]).default("concept"), sponsorEntity: z.string().max(255).optional(), knownProgramSummary: z.string().optional(), programUnitCount: z.number().int().min(0).optional(), programBuildingCount: z.number().int().min(0).optional(), programUnitsPerBuilding: z.number().int().min(0).optional(), programAreaSqFt: z.number().int().min(0).optional(), programFootprintDescription: z.string().optional(), factoryFoundationRelationship: z.string().optional(), factoryFoundationRelationshipState: z.enum(["linked", "contextual", "missing"]).default("missing"), totalProjectCost: z.number().int().min(0).optional(), totalProjectCostDataState: dataStateInput.default("missing"), capitalRequirement: z.number().int().min(0).optional(), capitalRequirementDataState: dataStateInput.default("missing"), targetCompletionAt: z.coerce.date().optional(), linkedFfProject: z.string().max(255).optional(), roiProjectId: z.number().int().nullable().optional(), description: z.string().optional(), notes: z.string().optional() });
const internalProjectCapitalNeedInput = z.object({ internalProjectId: z.number().int(), requirementName: z.string().min(1).max(255), requirementCategory: z.string().min(1).max(128).default("other"), amount: z.number().int().min(0).optional(), amountDataState: dataStateInput.default("missing"), notes: z.string().optional(), sortOrder: z.number().int().optional(), strategyTypes: z.array(z.enum(["equity", "facility_jv", "equipment_finance", "grants", "other"])).default([]) });
const projectEconomicsInput = z.object({ modelId: z.number().int(), inputArea: z.enum(["uses", "operations", "sources"]), inputCategory: z.string().min(1).max(128), inputName: z.string().min(1).max(255), value: z.number().int().optional(), valueUnit: z.enum(["usd", "units", "percentage_bps", "hours", "other"]).default("usd"), dataState: dataStateInput.default("missing"), sourceReference: z.string().max(500).optional(), effectiveAt: z.coerce.date().optional(), ownerName: z.string().max(255).optional(), linkedCapitalOpportunityId: z.number().int().nullable().optional(), notes: z.string().optional(), sortOrder: z.number().int().optional() });
const projectEconomicsMonthlyItemInput = z.object({ modelId: z.number().int(), monthIndex: z.number().int().min(1).max(36), phase: z.enum(["predevelopment", "design_entitlement", "construction", "building_completion", "lease_up_stabilization", "commissioning", "operating_ramp"]), category: z.enum(["capex", "draw", "operating_cash_flow", "debt_service", "grant_disbursement", "revenue_collections"]), amount: z.number().int().optional(), dataState: dataStateInput.default("missing"), sourceReference: z.string().max(500).optional(), effectiveAt: z.coerce.date().optional(), ownerName: z.string().max(255).optional(), notes: z.string().optional() });
const projectionScenarioInput = z.object({ modelId: z.number().int(), scenarioName: z.string().min(1).max(255), scenarioType: z.enum(["downside", "base", "upside", "custom"]), scenarioStatus: z.enum(["draft", "active", "archived"]).default("draft"), notes: z.string().optional() });
const projectionAssumptionInput = z.object({ scenarioId: z.number().int(), assumptionCategory: z.string().min(1).max(128), metric: z.string().min(1).max(128), value: z.number().int(), valueUnit: z.enum(["usd", "units", "percentage_bps", "months", "other"]).default("usd"), periodStartMonth: z.number().int().min(1).max(36).optional(), periodEndMonth: z.number().int().min(1).max(36).optional(), dataState: z.enum(["projected", "estimated"]), sourceReference: z.string().max(500).optional(), effectiveAt: z.coerce.date().optional(), ownerName: z.string().max(255).optional(), notes: z.string().optional(), sortOrder: z.number().int().optional() });
const projectionMonthlyLineInput = z.object({ scenarioId: z.number().int(), monthIndex: z.number().int().min(1).max(36), phase: z.enum(["predevelopment", "design_entitlement", "construction", "building_completion", "lease_up_stabilization", "commissioning", "operating_ramp", "stabilized_operations"]), metricCategory: z.enum(["revenue", "operating_cost", "capital_deployment", "financing_cost", "funding_draw", "ce_capital_contribution", "ce_distribution"]), deploymentCategory: z.enum(["land_site", "building", "furniture_fixtures_equipment", "equipment", "robotics_automation", "technology", "soft_costs", "contingency", "working_capital", "other"]).nullable().optional(), amount: z.number().int(), dataState: z.enum(["projected", "estimated"]), sourceReference: z.string().max(500).optional(), effectiveAt: z.coerce.date().optional(), ownerName: z.string().max(255).optional(), notes: z.string().optional() });
const researchApplyFields = ["thesis", "fitScore", "geography", "checkSize", "investorLanguage", "portfolioHighlights", "likelyObjections", "bestPitchAngle", "warmIntroPath", "assetClassPreference", "riskTolerance", "returnExpectations", "capitalPreference", "investmentHorizon", "decisionStructure", "decisionCycle", "communicationPreference", "draft"] as const;

const messageInput = z.object({
  initialSubject: z.string().min(1),
  initialBody: z.string().min(1),
  followUpSubject: z.string().min(1),
  followUpBody: z.string().min(1),
});

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
  }),
  fundraising: router({
    campaigns: protectedProcedure.query(({ ctx }) => listCampaigns(ctx.user.id)),
    createCampaign: protectedProcedure.input(campaignInput).mutation(({ ctx, input }) => createCampaign(ctx.user.id, input)),
    updateCampaign: protectedProcedure.input(z.object({ id: z.number().int(), name: z.string().min(1).optional(), groupName: z.string().min(1).max(128).optional(), sortOrder: z.number().int().optional(), funnelStage: z.string().optional(), targetCount: z.number().int().positive().optional(), status: z.enum(["planning", "active", "paused", "completed"]).optional() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateCampaign(ctx.user.id, id, patch); }),
    deleteCampaign: protectedProcedure.input(z.object({ id: z.number().int() })).mutation(({ ctx, input }) => deleteCampaign(ctx.user.id, input.id)),
    documents: protectedProcedure.query(({ ctx }) => listFundraisingDocuments(ctx.user.id)),
    campaignDocuments: protectedProcedure.query(({ ctx }) => listCampaignDocumentLinks(ctx.user.id)),
    uploadDocument: protectedProcedure.input(z.object({ name: z.string().min(1).max(255), category: z.string().min(1).max(128).default("Supporting material"), version: z.string().min(1).max(64).default("v1"), audience: z.string().min(1).max(128).default("General"), purpose: z.string().min(1).max(255).default("General fundraising"), replacesDocumentId: z.number().int().optional(), description: z.string().max(4000).optional(), mimeType: z.enum(["application/pdf", "application/vnd.openxmlformats-officedocument.presentationml.presentation", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]), contentBase64: z.string().min(1).max(18000000) })).mutation(async ({ ctx, input }) => {
      const bytes = Buffer.from(input.contentBase64, "base64");
      if (bytes.length === 0 || bytes.length > 12 * 1024 * 1024) throw new TRPCError({ code: "PAYLOAD_TOO_LARGE", message: "Documents must be between 1 byte and 12 MB." });
      const safeName = input.name.replace(/[^a-zA-Z0-9._ -]/g, "_");
      const stored = await storagePut(`${ctx.user.id}/fundraising-documents/${safeName}`, bytes, input.mimeType);
      const document = await createFundraisingDocument(ctx.user.id, { name: safeName, category: input.category, version: input.version, audience: input.audience, purpose: input.purpose, replacesDocumentId: input.replacesDocumentId, description: input.description, status: "current", mimeType: input.mimeType, storageKey: stored.key, storageUrl: stored.url, sizeBytes: bytes.length });
      if (input.replacesDocumentId) await updateFundraisingDocument(ctx.user.id, input.replacesDocumentId, { status: "archived" });
      return document;
    }),
    updateDocument: protectedProcedure.input(z.object({ id: z.number().int(), category: z.string().min(1).max(128).optional(), version: z.string().min(1).max(64).optional(), audience: z.string().min(1).max(128).optional(), purpose: z.string().min(1).max(255).optional(), description: z.string().max(4000).nullable().optional(), status: z.enum(["current", "archived"]).optional() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateFundraisingDocument(ctx.user.id, id, patch); }),
    linkDocument: protectedProcedure.input(z.object({ campaignId: z.number().int(), documentId: z.number().int() })).mutation(({ ctx, input }) => linkDocumentToCampaign(ctx.user.id, input.campaignId, input.documentId)),
    unlinkDocument: protectedProcedure.input(z.object({ campaignId: z.number().int(), documentId: z.number().int() })).mutation(({ ctx, input }) => unlinkDocumentFromCampaign(ctx.user.id, input.campaignId, input.documentId)),
    deleteDocument: protectedProcedure.input(z.object({ documentId: z.number().int() })).mutation(({ ctx, input }) => deleteFundraisingDocument(ctx.user.id, input.documentId)),
    investorDocuments: protectedProcedure.input(z.object({ contactId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listInvestorDocumentLinks(ctx.user.id, input?.contactId)),
    linkInvestorDocument: protectedProcedure.input(z.object({ contactId: z.number().int(), documentId: z.number().int() })).mutation(({ ctx, input }) => linkDocumentToInvestor(ctx.user.id, input.contactId, input.documentId)),
    unlinkInvestorDocument: protectedProcedure.input(z.object({ contactId: z.number().int(), documentId: z.number().int() })).mutation(({ ctx, input }) => unlinkDocumentFromInvestor(ctx.user.id, input.contactId, input.documentId)),
    bootstrapCapitalFormation: protectedProcedure.mutation(({ ctx }) => bootstrapEquityCapitalOpportunities(ctx.user.id)),
    jvPartnerProspects: protectedProcedure.query(({ ctx }) => listJvPartnerProspects(ctx.user.id)),
    importTexasJvMasterUniverse: protectedProcedure.mutation(({ ctx }) => {
      const records = loadTexasJvMasterUniverse().map((record) => {
        const strategicFit = record.status === "prospect" ? "Medium" as const : "Low" as const;
        const routing = scoreJvProspect({ partnerType: record.partnerType as any, region: record.region as any, strategicFit, landContributionPotential: "Unknown", capitalContributionPotential: "Unknown", developmentContributionPotential: "Unknown", facilityContributionPotential: "Unknown" });
        return { ...record, strategicFit, priority: routing.priority, priorityRationale: routing.rationale };
      });
      return importTexasJvMasterUniverse(ctx.user.id, records);
    }),
    createJvPartnerProspect: protectedProcedure.input(jvProspectInput).mutation(({ ctx, input }) => { const routing = scoreJvProspect({ ...input, partnerType: input.partnerType as any, region: input.region as any }); return createJvPartnerProspect(ctx.user.id, { ...input, priority: routing.priority, priorityRationale: routing.rationale }); }),
    updateJvPartnerProspect: protectedProcedure.input(jvProspectInput.partial().extend({ id: z.number().int() })).mutation(async ({ ctx, input }) => { const { id, ...patch } = input; const prior = await getJvPartnerProspect(ctx.user.id, id); if (!prior) throw new TRPCError({ code: "NOT_FOUND", message: "JV prospect not found." }); const routing = scoreJvProspect({ partnerType: patch.partnerType ?? prior.partnerType as any, region: patch.region ?? prior.region as any, assetFocus: patch.assetFocus ?? prior.assetFocus, developmentFocus: patch.developmentFocus ?? prior.developmentFocus, jvExperience: patch.jvExperience ?? prior.jvExperience, landContributionPotential: patch.landContributionPotential ?? prior.landContributionPotential, capitalContributionPotential: patch.capitalContributionPotential ?? prior.capitalContributionPotential, developmentContributionPotential: patch.developmentContributionPotential ?? prior.developmentContributionPotential, facilityContributionPotential: patch.facilityContributionPotential ?? prior.facilityContributionPotential, strategicFit: patch.strategicFit ?? prior.strategicFit as any, jvThesis: patch.jvThesis ?? prior.jvThesis }); return updateJvPartnerProspect(ctx.user.id, id, { ...patch, priority: routing.priority, priorityRationale: routing.rationale }); }),
    convertJvPartnerProspect: protectedProcedure.input(z.object({ id: z.number().int() })).mutation(({ ctx, input }) => convertJvProspectToCapitalOpportunity(ctx.user.id, input.id)),
    capitalBuckets: protectedProcedure.query(({ ctx }) => listCapitalBuckets(ctx.user.id)),
    updateCapitalBucket: protectedProcedure.input(z.object({ capitalPath: capitalPathInput, targetAmount: z.number().int().min(0).optional(), description: z.string().nullable().optional() })).mutation(async ({ ctx, input }) => { await ensureCapitalBuckets(ctx.user.id); const { capitalPath, ...patch } = input; return updateCapitalBucket(ctx.user.id, capitalPath, patch); }),
    capitalOpportunities: protectedProcedure.input(z.object({ capitalPath: capitalPathInput.optional() }).optional()).query(({ ctx, input }) => listCapitalOpportunities(ctx.user.id, input?.capitalPath)),
    createCapitalOpportunity: protectedProcedure.input(capitalOpportunityInput).mutation(({ ctx, input }) => createCapitalOpportunity(ctx.user.id, input)),
    updateCapitalOpportunity: protectedProcedure.input(capitalOpportunityInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateCapitalOpportunity(ctx.user.id, id, patch); }),
    capitalOpportunityDocuments: protectedProcedure.input(z.object({ capitalOpportunityId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listCapitalOpportunityDocumentLinks(ctx.user.id, input?.capitalOpportunityId)),
    linkCapitalOpportunityDocument: protectedProcedure.input(z.object({ capitalOpportunityId: z.number().int(), documentId: z.number().int() })).mutation(({ ctx, input }) => linkDocumentToCapitalOpportunity(ctx.user.id, input.capitalOpportunityId, input.documentId)),
    unlinkCapitalOpportunityDocument: protectedProcedure.input(z.object({ capitalOpportunityId: z.number().int(), documentId: z.number().int() })).mutation(({ ctx, input }) => unlinkDocumentFromCapitalOpportunity(ctx.user.id, input.capitalOpportunityId, input.documentId)),
    facilityJvDetail: protectedProcedure.input(z.object({ capitalOpportunityId: z.number().int() })).query(({ ctx, input }) => getFacilityJvDetail(ctx.user.id, input.capitalOpportunityId)),
    saveFacilityJvDetail: protectedProcedure.input(facilityJvDetailInput).mutation(({ ctx, input }) => { const { capitalOpportunityId, ...patch } = input; return upsertFacilityJvDetail(ctx.user.id, capitalOpportunityId, patch); }),
    equipmentFinanceDetail: protectedProcedure.input(z.object({ capitalOpportunityId: z.number().int() })).query(({ ctx, input }) => getEquipmentFinanceDetail(ctx.user.id, input.capitalOpportunityId)),
    equipmentFinanceDetails: protectedProcedure.query(({ ctx }) => listEquipmentFinanceDetails(ctx.user.id)),
    saveEquipmentFinanceDetail: protectedProcedure.input(equipmentFinanceDetailInput).mutation(({ ctx, input }) => { const { capitalOpportunityId, ...patch } = input; return upsertEquipmentFinanceDetail(ctx.user.id, capitalOpportunityId, patch); }),
    equipmentRentalVendors: protectedProcedure.query(({ ctx }) => listEquipmentRentalVendors(ctx.user.id)),
    importTexasEquipmentRentalSeed: protectedProcedure.mutation(({ ctx }) => importTexasEquipmentRentalMasterUniverse(ctx.user.id)),
    createEquipmentRentalVendor: protectedProcedure.input(equipmentRentalVendorInput).mutation(({ ctx, input }) => { const scoring = scoreEquipmentRentalVendor(input); return createEquipmentRentalVendor(ctx.user.id, { ...input, priority: scoring.priority, priorityRationale: scoring.rationale }); }),
    updateEquipmentRentalVendor: protectedProcedure.input(equipmentRentalVendorInput.partial().extend({ id: z.number().int() })).mutation(async ({ ctx, input }) => { const { id, ...patch } = input; const prior = await getEquipmentRentalVendor(ctx.user.id, id); if (!prior) throw new TRPCError({ code: "NOT_FOUND", message: "Rental vendor not found." }); const scoring = scoreEquipmentRentalVendor({ equipmentCategories: patch.equipmentCategories ?? prior.equipmentCategories, region: patch.region ?? prior.region, deliveryAvailable: patch.deliveryAvailable ?? prior.deliveryAvailable, pickupAvailable: patch.pickupAvailable ?? prior.pickupAvailable, operatorServices: patch.operatorServices ?? prior.operatorServices, shortTermRental: patch.shortTermRental ?? prior.shortTermRental, longTermRental: patch.longTermRental ?? prior.longTermRental, serviceMaintenance: patch.serviceMaintenance ?? prior.serviceMaintenance, strategicFit: patch.strategicFit ?? prior.strategicFit }); return updateEquipmentRentalVendor(ctx.user.id, id, { ...patch, priority: scoring.priority, priorityRationale: scoring.rationale }); }),
    equipmentRentalRequirements: protectedProcedure.query(({ ctx }) => listEquipmentRentalRequirements(ctx.user.id)),
    createEquipmentRentalRequirement: protectedProcedure.input(equipmentRentalRequirementInput).mutation(({ ctx, input }) => createEquipmentRentalRequirement(ctx.user.id, input)),
    updateEquipmentRentalRequirement: protectedProcedure.input(equipmentRentalRequirementInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateEquipmentRentalRequirement(ctx.user.id, id, patch); }),
    equipmentRentalQuotes: protectedProcedure.input(z.object({ requirementId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listEquipmentRentalQuotes(ctx.user.id, input?.requirementId)),
    createEquipmentRentalQuote: protectedProcedure.input(equipmentRentalQuoteInput).mutation(({ ctx, input }) => createEquipmentRentalQuote(ctx.user.id, input)),
    updateEquipmentRentalQuote: protectedProcedure.input(equipmentRentalQuoteInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateEquipmentRentalQuote(ctx.user.id, id, patch); }),
    equipmentActiveRentals: protectedProcedure.query(({ ctx }) => listEquipmentActiveRentals(ctx.user.id)),
    createEquipmentActiveRental: protectedProcedure.input(equipmentActiveRentalInput).mutation(({ ctx, input }) => createEquipmentActiveRental(ctx.user.id, input)),
    updateEquipmentActiveRental: protectedProcedure.input(equipmentActiveRentalInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateEquipmentActiveRental(ctx.user.id, id, patch); }),
    grantDetail: protectedProcedure.input(z.object({ capitalOpportunityId: z.number().int() })).query(({ ctx, input }) => getGrantDetail(ctx.user.id, input.capitalOpportunityId)),
    saveGrantDetail: protectedProcedure.input(grantDetailInput).mutation(({ ctx, input }) => { const { capitalOpportunityId, ...patch } = input; return upsertGrantDetail(ctx.user.id, capitalOpportunityId, patch); }),
    grantFundingPrograms: protectedProcedure.query(({ ctx }) => listGrantFundingPrograms(ctx.user.id)),
    importTexasGrantsIncentivesMasterUniverse: protectedProcedure.mutation(({ ctx }) => importTexasGrantsIncentivesMasterUniverse(ctx.user.id, loadTexasGrantsIncentivesMasterUniverse())),
    createGrantFundingProgram: protectedProcedure.input(grantFundingProgramInput).mutation(({ ctx, input }) => createGrantFundingProgram(ctx.user.id, input)),
    updateGrantFundingProgram: protectedProcedure.input(grantFundingProgramInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateGrantFundingProgram(ctx.user.id, id, patch); }),
    grantFundingOpportunities: protectedProcedure.query(({ ctx }) => listGrantFundingOpportunities(ctx.user.id)),
    createGrantFundingOpportunity: protectedProcedure.input(grantFundingOpportunityInput).mutation(({ ctx, input }) => createGrantFundingOpportunity(ctx.user.id, input)),
    updateGrantFundingOpportunity: protectedProcedure.input(grantFundingOpportunityInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateGrantFundingOpportunity(ctx.user.id, id, patch); }),
    grantFundingApplications: protectedProcedure.query(({ ctx }) => listGrantFundingApplications(ctx.user.id)),
    createGrantFundingApplication: protectedProcedure.input(grantFundingApplicationInput).mutation(({ ctx, input }) => createGrantFundingApplication(ctx.user.id, input)),
    updateGrantFundingApplication: protectedProcedure.input(grantFundingApplicationInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateGrantFundingApplication(ctx.user.id, id, patch); }),
    grantFundingAwards: protectedProcedure.query(({ ctx }) => listGrantFundingAwards(ctx.user.id)),
    saveGrantFundingAward: protectedProcedure.input(grantFundingAwardInput).mutation(({ ctx, input }) => saveGrantFundingAward(ctx.user.id, input)),
    grantAwardDisbursements: protectedProcedure.query(({ ctx }) => listGrantAwardDisbursements(ctx.user.id)),
    createGrantAwardDisbursement: protectedProcedure.input(grantAwardDisbursementInput).mutation(({ ctx, input }) => createGrantAwardDisbursement(ctx.user.id, input)),
    grantComplianceItems: protectedProcedure.query(({ ctx }) => listGrantComplianceItems(ctx.user.id)),
    createGrantComplianceItem: protectedProcedure.input(grantComplianceItemInput).mutation(({ ctx, input }) => createGrantComplianceItem(ctx.user.id, input)),
    updateGrantComplianceItem: protectedProcedure.input(grantComplianceItemInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateGrantComplianceItem(ctx.user.id, id, patch); }),
    roiProjects: protectedProcedure.query(({ ctx }) => listRoiProjects(ctx.user.id)),
    roiCrossDomainSnapshot: protectedProcedure.input(z.object({ projectId: z.number().int() })).query(({ ctx, input }) => getCrossDomainRoiSnapshot(ctx.user.id, input.projectId)),
    createRoiProject: protectedProcedure.input(roiProjectInput).mutation(({ ctx, input }) => createRoiProject(ctx.user.id, input)),
    updateRoiProject: protectedProcedure.input(roiProjectInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateRoiProject(ctx.user.id, id, patch); }),
    roiCapitalSources: protectedProcedure.input(z.object({ projectId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listRoiCapitalSources(ctx.user.id, input?.projectId)),
    createRoiCapitalSource: protectedProcedure.input(roiCapitalSourceInput).mutation(({ ctx, input }) => createRoiCapitalSource(ctx.user.id, input)),
    updateRoiCapitalSource: protectedProcedure.input(roiCapitalSourceInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateRoiCapitalSource(ctx.user.id, id, patch); }),
    roiCashFlows: protectedProcedure.input(z.object({ projectId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listRoiCashFlows(ctx.user.id, input?.projectId)),
    saveRoiCashFlow: protectedProcedure.input(roiCashFlowInput).mutation(({ ctx, input }) => upsertRoiCashFlow(ctx.user.id, input)),
    roiScenarios: protectedProcedure.input(z.object({ projectId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listRoiScenarios(ctx.user.id, input?.projectId)),
    createRoiScenario: protectedProcedure.input(roiScenarioInput).mutation(({ ctx, input }) => createRoiScenario(ctx.user.id, input)),
    updateRoiScenario: protectedProcedure.input(roiScenarioInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateRoiScenario(ctx.user.id, id, patch); }),
    internalProjects: protectedProcedure.query(({ ctx }) => listInternalProjects(ctx.user.id)),
    seedInitialInternalProjects: protectedProcedure.mutation(({ ctx }) => seedInitialInternalProjects(ctx.user.id)),
    createInternalProject: protectedProcedure.input(internalProjectInput).mutation(({ ctx, input }) => createInternalProject(ctx.user.id, input)),
    updateInternalProject: protectedProcedure.input(internalProjectInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateInternalProject(ctx.user.id, id, patch); }),
    internalProjectCapitalNeeds: protectedProcedure.input(z.object({ internalProjectId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listInternalProjectCapitalNeeds(ctx.user.id, input?.internalProjectId)),
    internalProjectCapitalNeedStrategies: protectedProcedure.input(z.object({ capitalNeedId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listInternalProjectCapitalNeedStrategies(ctx.user.id, input?.capitalNeedId)),
    saveInternalProjectCapitalNeed: protectedProcedure.input(internalProjectCapitalNeedInput.extend({ id: z.number().int().optional() })).mutation(({ ctx, input }) => saveInternalProjectCapitalNeed(ctx.user.id, input)),
    internalProjectCapitalStack: protectedProcedure.input(z.object({ internalProjectId: z.number().int() })).query(({ ctx, input }) => getInternalProjectCapitalStack(ctx.user.id, input.internalProjectId)),
    internalProjectDocuments: protectedProcedure.input(z.object({ internalProjectId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listInternalProjectDocumentLinks(ctx.user.id, input?.internalProjectId)),
    linkInternalProjectDocument: protectedProcedure.input(z.object({ internalProjectId: z.number().int(), documentId: z.number().int() })).mutation(({ ctx, input }) => linkDocumentToInternalProject(ctx.user.id, input.internalProjectId, input.documentId)),
    unlinkInternalProjectDocument: protectedProcedure.input(z.object({ internalProjectId: z.number().int(), documentId: z.number().int() })).mutation(({ ctx, input }) => unlinkDocumentFromInternalProject(ctx.user.id, input.internalProjectId, input.documentId)),
    projectEconomicsModel: protectedProcedure.input(z.object({ internalProjectId: z.number().int() })).query(({ ctx, input }) => getProjectEconomicsModelForProject(ctx.user.id, input.internalProjectId)),
    initializeProjectEconomicsModel: protectedProcedure.input(z.object({ internalProjectId: z.number().int() })).mutation(({ ctx, input }) => initializeProjectEconomicsModel(ctx.user.id, input.internalProjectId)),
    initializeChappellProjectEconomicsModel: protectedProcedure.input(z.object({ internalProjectId: z.number().int() })).mutation(({ ctx, input }) => initializeChappellProjectEconomicsModel(ctx.user.id, input.internalProjectId)),
    projectEconomicsInputs: protectedProcedure.input(z.object({ modelId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listProjectEconomicsInputs(ctx.user.id, input?.modelId)),
    saveProjectEconomicsInput: protectedProcedure.input(projectEconomicsInput.extend({ id: z.number().int().optional() })).mutation(({ ctx, input }) => saveProjectEconomicsInput(ctx.user.id, input)),
    projectEconomicsMonthlyItems: protectedProcedure.input(z.object({ modelId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listProjectEconomicsMonthlyItems(ctx.user.id, input?.modelId)),
    saveProjectEconomicsMonthlyItem: protectedProcedure.input(projectEconomicsMonthlyItemInput).mutation(({ ctx, input }) => saveProjectEconomicsMonthlyItem(ctx.user.id, input)),
    projectEconomicsReadiness: protectedProcedure.input(z.object({ modelId: z.number().int() })).query(({ ctx, input }) => getProjectEconomicsReadiness(ctx.user.id, input.modelId)),
    projectEconomicsInputDocuments: protectedProcedure.input(z.object({ modelInputId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listProjectEconomicsInputDocuments(ctx.user.id, input?.modelInputId)),
    linkProjectEconomicsInputDocument: protectedProcedure.input(z.object({ modelInputId: z.number().int(), documentId: z.number().int() })).mutation(({ ctx, input }) => linkDocumentToProjectEconomicsInput(ctx.user.id, input.modelInputId, input.documentId)),
    unlinkProjectEconomicsInputDocument: protectedProcedure.input(z.object({ modelInputId: z.number().int(), documentId: z.number().int() })).mutation(({ ctx, input }) => unlinkDocumentFromProjectEconomicsInput(ctx.user.id, input.modelInputId, input.documentId)),
    projectionScenarios: protectedProcedure.input(z.object({ modelId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listProjectionScenarios(ctx.user.id, input?.modelId)),
    ensureProjectionScenarioShells: protectedProcedure.input(z.object({ modelId: z.number().int() })).mutation(({ ctx, input }) => ensureProjectionScenarioShells(ctx.user.id, input.modelId)),
    createProjectionScenario: protectedProcedure.input(projectionScenarioInput).mutation(({ ctx, input }) => createProjectionScenario(ctx.user.id, input)),
    updateProjectionScenario: protectedProcedure.input(projectionScenarioInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateProjectionScenario(ctx.user.id, id, patch); }),
    projectionAssumptions: protectedProcedure.input(z.object({ scenarioId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listProjectionAssumptions(ctx.user.id, input?.scenarioId)),
    saveProjectionAssumption: protectedProcedure.input(projectionAssumptionInput.extend({ id: z.number().int().optional() })).mutation(({ ctx, input }) => saveProjectionAssumption(ctx.user.id, input)),
    projectionMonthlyLines: protectedProcedure.input(z.object({ scenarioId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listProjectionMonthlyLines(ctx.user.id, input?.scenarioId)),
    saveProjectionMonthlyLine: protectedProcedure.input(projectionMonthlyLineInput).mutation(({ ctx, input }) => saveProjectionMonthlyLine(ctx.user.id, input)),
    projectionSnapshot: protectedProcedure.input(z.object({ modelId: z.number().int() })).query(({ ctx, input }) => getProjectionSnapshot(ctx.user.id, input.modelId)),
    historicalPlanningBudgetComparison: protectedProcedure.query(({ ctx }) => getHistoricalPlanningBudgetComparison(ctx.user.id)),
    financialOsPortfolioSnapshot: protectedProcedure.query(({ ctx }) => getFinancialOsPortfolioSnapshot(ctx.user.id)),
    projectPlanningWbsLines: protectedProcedure.input(z.object({ scenarioId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listProjectPlanningWbsLines(ctx.user.id, input?.scenarioId)),
    projectPlanningWbsSummary: protectedProcedure.input(z.object({ scenarioId: z.number().int() })).query(({ ctx, input }) => getProjectPlanningWbsSummary(ctx.user.id, input.scenarioId)),
    seedCedarwoodHistoricalPlanningWbs: protectedProcedure.input(z.object({ scenarioId: z.number().int() })).mutation(({ ctx, input }) => seedCedarwoodHistoricalPlanningWbs(ctx.user.id, input.scenarioId)),
    cedarwoodPlanningScheduleMonths: protectedProcedure.input(z.object({ scenarioId: z.number().int() })).query(({ ctx, input }) => listProjectPlanningScheduleMonths(ctx.user.id, input.scenarioId)),
    cedarwoodPlanningFinancingTerms: protectedProcedure.input(z.object({ scenarioId: z.number().int() })).query(({ ctx, input }) => getProjectPlanningFinancingTerms(ctx.user.id, input.scenarioId)),
    cedarwoodScheduleFinancingSnapshot: protectedProcedure.input(z.object({ scenarioId: z.number().int() })).query(({ ctx, input }) => getCedarwoodScheduleFinancingSnapshot(ctx.user.id, input.scenarioId)),
    cedarwoodScenarioUnitMix: protectedProcedure.input(z.object({ scenarioId: z.number().int() })).query(({ ctx, input }) => listCedarwoodScenarioUnitMix(ctx.user.id, input.scenarioId)),
    saveCedarwoodScenarioUnitMix: protectedProcedure.input(cedarwoodScenarioUnitMixInput).mutation(({ ctx, input }) => saveCedarwoodScenarioUnitMix(ctx.user.id, input)),
    cedarwoodScenarioMatrix: protectedProcedure.input(z.object({ modelId: z.number().int() })).query(({ ctx, input }) => getCedarwoodScenarioMatrix(ctx.user.id, input.modelId)),
    cloneCedarwoodScenario: protectedProcedure.input(cedarwoodScenarioCloneInput).mutation(({ ctx, input }) => cloneCedarwoodScenario(ctx.user.id, input.sourceScenarioId, input.scenarioName)),
    saveCedarwoodPlanningSchedule: protectedProcedure.input(cedarwoodPlanningScheduleInput).mutation(({ ctx, input }) => saveProjectPlanningScheduleMonths(ctx.user.id, input)),
    saveCedarwoodPlanningFinancing: protectedProcedure.input(cedarwoodPlanningFinancingInput).mutation(({ ctx, input }) => saveProjectPlanningFinancingTerms(ctx.user.id, input)),
    roiReturnDetails: protectedProcedure.query(({ ctx }) => listRoiReturnDetails(ctx.user.id)),
    saveRoiEquityReturnDetail: protectedProcedure.input(roiEquityReturnInput).mutation(({ ctx, input }) => { const { capitalSourceId, ...patch } = input; return upsertRoiEquityReturnDetail(ctx.user.id, capitalSourceId, patch); }),
    saveRoiJvReturnDetail: protectedProcedure.input(roiJvReturnInput).mutation(({ ctx, input }) => { const { capitalSourceId, ...patch } = input; return upsertRoiJvReturnDetail(ctx.user.id, capitalSourceId, patch); }),
    saveRoiEquipmentReturnDetail: protectedProcedure.input(roiEquipmentReturnInput).mutation(({ ctx, input }) => { const { capitalSourceId, ...patch } = input; return upsertRoiEquipmentReturnDetail(ctx.user.id, capitalSourceId, patch); }),
    saveRoiGrantReturnDetail: protectedProcedure.input(roiGrantReturnInput).mutation(({ ctx, input }) => { const { capitalSourceId, ...patch } = input; return upsertRoiGrantReturnDetail(ctx.user.id, capitalSourceId, patch); }),
    roiJvContributionComponents: protectedProcedure.input(z.object({ capitalSourceId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listRoiJvContributionComponents(ctx.user.id, input?.capitalSourceId)),
    createRoiJvContributionComponent: protectedProcedure.input(roiContributionComponentInput).mutation(({ ctx, input }) => createRoiJvContributionComponent(ctx.user.id, input)),
    updateRoiJvContributionComponent: protectedProcedure.input(roiContributionComponentInput.partial().extend({ id: z.number().int() })).mutation(({ ctx, input }) => { const { id, ...patch } = input; return updateRoiJvContributionComponent(ctx.user.id, id, patch); }),
    tasks: protectedProcedure.query(({ ctx }) => listTasks(ctx.user.id)),
    createTask: protectedProcedure.input(taskInput).mutation(({ ctx, input }) => createTask(ctx.user.id, input)),
    updateTask: protectedProcedure.input(z.object({ id: z.number().int(), status: z.enum(["open", "in_progress", "done", "snoozed"]) })).mutation(({ ctx, input }) => updateTask(ctx.user.id, input.id, input.status)),
    meetings: protectedProcedure.query(({ ctx }) => listMeetings(ctx.user.id)),
    createMeeting: protectedProcedure.input(meetingInput).mutation(({ ctx, input }) => createMeeting(ctx.user.id, input)),
    analytics: protectedProcedure.query(({ ctx }) => getFundraisingAnalytics(ctx.user.id)),
    investorEvents: protectedProcedure.input(z.object({ contactId: z.number().int().optional() }).optional()).query(({ ctx, input }) => listInvestorEvents(ctx.user.id, input?.contactId)),
    researchProposals: protectedProcedure.input(z.object({ contactId: z.number().int() })).query(({ ctx, input }) => listInvestorResearchProposals(ctx.user.id, input.contactId)),
    researchSources: protectedProcedure.input(z.object({ proposalId: z.number().int() })).query(({ ctx, input }) => listInvestorResearchSources(ctx.user.id, input.proposalId)),
    researchInvestor: protectedProcedure.input(z.object({ contactId: z.number().int(), sourceUrls: z.array(z.string().min(4).max(2048)).min(1).max(4) })).mutation(async ({ ctx, input }) => {
      const contact = await getInvestorContact(ctx.user.id, input.contactId);
      if (!contact) throw new TRPCError({ code: "NOT_FOUND", message: "Investor contact not found." });
      try {
        const sources = await fetchPublicResearchSources(input.sourceUrls);
        const proposal = await generateInvestorResearchProposal({ firmName: contact.firmName, contactName: contact.contactName, existingThesis: contact.thesis, sources });
        const saved = await createInvestorResearchProposal(ctx.user.id, contact.id, proposal, sources);
        await addOutreachEvent(ctx.user.id, contact.id, "research_proposed", `Public-source research proposal created from ${sources.length} approved source${sources.length === 1 ? "" : "s"}.`);
        return saved;
      } catch (error) {
        await addOutreachEvent(ctx.user.id, contact.id, "research_failed", error instanceof Error ? error.message : "Investor research failed.");
        throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Investor research failed." });
      }
    }),
    applyResearchProposal: protectedProcedure.input(z.object({ proposalId: z.number().int(), fields: z.array(z.enum(researchApplyFields)).min(1) })).mutation(async ({ ctx, input }) => {
      const proposal = await getInvestorResearchProposal(ctx.user.id, input.proposalId);
      if (!proposal) throw new TRPCError({ code: "NOT_FOUND", message: "Research proposal not found." });
      const patch: Record<string, unknown> = {};
      const setIfPresent = (field: string, value: unknown) => { if (value !== null && value !== undefined && value !== "") patch[field] = value; };
      for (const field of input.fields) {
        if (field === "fitScore") setIfPresent("fitScore", proposal.suggestedFitScore);
        else if (field === "checkSize") { setIfPresent("checkSizeMin", proposal.checkSizeMin); setIfPresent("checkSizeMax", proposal.checkSizeMax); }
        else if (field === "draft") { setIfPresent("initialSubject", proposal.draftSubject); setIfPresent("initialBody", proposal.draftBody); }
        else setIfPresent(field, proposal[field]);
      }
      if (!Object.keys(patch).length) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "The selected fields have no supported research evidence to apply." });
      const updated = await updateInvestorContact(ctx.user.id, proposal.contactId, patch);
      await updateInvestorResearchProposalStatus(ctx.user.id, proposal.id, "applied");
      await addOutreachEvent(ctx.user.id, proposal.contactId, "research_applied", `Approved research fields applied: ${input.fields.join(", ")}. No email was sent.`);
      return updated;
    }),
    dismissResearchProposal: protectedProcedure.input(z.object({ proposalId: z.number().int() })).mutation(async ({ ctx, input }) => {
      const proposal = await getInvestorResearchProposal(ctx.user.id, input.proposalId);
      if (!proposal) throw new TRPCError({ code: "NOT_FOUND", message: "Research proposal not found." });
      const updated = await updateInvestorResearchProposalStatus(ctx.user.id, input.proposalId, "dismissed");
      await addOutreachEvent(ctx.user.id, proposal.contactId, "research_dismissed", "Research proposal dismissed; no investor fields changed.");
      return updated;
    }),
    aiDraft: protectedProcedure.input(z.object({ firmName: z.string().min(1), thesis: z.string().optional(), geography: z.string().optional(), checkSizeMin: z.number().int().optional(), checkSizeMax: z.number().int().optional(), relationshipStage: z.string().optional() })).mutation(({ input }) => generateInvestorDraft(input)),
    aiClassify: protectedProcedure.input(z.object({ firmName: z.string().min(1), thesis: z.string().optional(), fitScore: z.number().int().optional(), relationshipStage: z.string().optional(), geography: z.string().optional() })).mutation(({ input }) => classifyInvestor(input)),
    aiSummarize: protectedProcedure.input(z.object({ firmName: z.string().min(1), events: z.array(z.object({ kind: z.string(), detail: z.string().optional().nullable(), createdAt: z.string() })) })).mutation(({ input }) => summarizeInvestorHistory(input)),
  }),
  outreach: router({
    gmailStatus: protectedProcedure.query(async ({ ctx }) => (await getGmailConnection(ctx.user.id)) ?? null),
    list: protectedProcedure.query(async ({ ctx }) => listInvestorContacts(ctx.user.id)),
    create: protectedProcedure.input(contactInput).mutation(async ({ ctx, input }) => {
      const result = await createInvestorContact(ctx.user.id, { ...input, status: "new" });
      if (result.duplicate) throw new TRPCError({ code: "CONFLICT", message: "This email is already in your outreach list." });
      return { success: true };
    }),
    updateProfile: protectedProcedure.input(z.object({ id: z.number().int(), relationshipStage: z.enum(["identified", "researched", "contacted", "engaged", "meeting", "diligence", "committed", "passed"]).optional(), checkSizeMin: z.number().int().optional(), checkSizeMax: z.number().int().optional(), geography: z.string().optional(), relationshipOwner: z.string().optional(), nextAction: z.string().optional(), nextActionDueAt: z.coerce.date().optional(), source: z.string().optional(), notes: z.string().optional(), campaignId: z.number().int().optional(), investorLanguage: z.string().max(255).optional(), portfolioHighlights: z.string().optional(), likelyObjections: z.string().optional(), bestPitchAngle: z.string().optional(), warmIntroPath: z.string().optional(), assetClassPreference: z.string().max(255).optional(), geographicPreference: z.string().max(255).optional(), riskTolerance: z.string().max(128).optional(), returnExpectations: z.string().max(255).optional(), capitalPreference: z.string().max(128).optional(), investmentHorizon: z.string().max(128).optional(), decisionStructure: z.string().optional(), decisionCycle: z.string().max(128).optional(), communicationPreference: z.string().max(255).optional(), relationshipStrength: z.string().max(128).optional(), historicalCommitments: z.string().optional(), relevantProjects: z.string().optional() })).mutation(async ({ ctx, input }) => updateInvestorContact(ctx.user.id, input.id, input)),
    saveMessages: protectedProcedure.input(z.object({ id: z.number().int(), ...messageInput.shape })).mutation(async ({ ctx, input }) => {
      const followUpDueAt = new Date();
      followUpDueAt.setMonth(followUpDueAt.getMonth() + 6);
      const updated = await updateInvestorContact(ctx.user.id, input.id, {
        initialSubject: input.initialSubject,
        initialBody: input.initialBody,
        followUpSubject: input.followUpSubject,
        followUpBody: input.followUpBody,
        followUpDueAt,
        status: "drafted",
      });
      await addOutreachEvent(ctx.user.id, input.id, "drafted", "Initial outreach and six-month follow-up drafted");
      return updated;
    }),
    setStatus: protectedProcedure.input(z.object({ id: z.number().int(), status: z.enum(["new", "drafted", "approved", "sent", "replied", "opted_out", "bounced", "paused"]) })).mutation(async ({ ctx, input }) => {
      const updated = await updateInvestorContact(ctx.user.id, input.id, { status: input.status });
      await addOutreachEvent(ctx.user.id, input.id, input.status, `Status changed to ${input.status}`);
      return updated;
    }),
    markSent: protectedProcedure.input(z.object({ id: z.number().int(), message: z.enum(["initial", "followup"]) })).mutation(async ({ ctx, input }) => {
      const gmail = await getGmailConnection(ctx.user.id);
      if (!canSendFromGmailStatus(Boolean(gmail))) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Gmail sending is not configured. Connect Gmail before sending." });
      const contact = await getInvestorContact(ctx.user.id, input.id);
      if (!contact) throw new TRPCError({ code: "NOT_FOUND", message: "Investor contact not found." });
      if (!canSendToContactStatus(contact.status)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "This contact is suppressed from outreach." });
      const subject = input.message === "initial" ? contact.initialSubject : contact.followUpSubject;
      const body = input.message === "initial" ? contact.initialBody : contact.followUpBody;
      if (!subject || !body) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Draft the message before sending." });
      const selectedIds = new Set((await listInvestorDocumentLinks(ctx.user.id, contact.id)).map((link) => link.documentId));
      const selectedDocuments = (await listFundraisingDocuments(ctx.user.id)).filter((document) => selectedIds.has(document.id) && document.status === "current");
      const attachments = await Promise.all(selectedDocuments.map(async (document) => { const response = await fetch(await storageGetSignedUrl(document.storageKey)); if (!response.ok) throw new Error(`Unable to load ${document.name} for attachment.`); return { name: document.name, mimeType: document.mimeType, content: Buffer.from(await response.arrayBuffer()) }; }));
      try { await sendGmailMessage(ctx.user.id, contact.email, subject, body, attachments); }
      catch (error) { throw new TRPCError({ code: "BAD_GATEWAY", message: error instanceof Error ? error.message : "Gmail send failed." }); }
      const patch = input.message === "initial" ? { status: "sent" as const, initialSentAt: new Date() } : { status: "sent" as const, followUpSentAt: new Date() };
      const updated = await updateInvestorContact(ctx.user.id, input.id, patch);
      await addOutreachEvent(ctx.user.id, input.id, `${input.message}_sent`, "Marked sent after configured Gmail send");
      return updated;
    }),
  }),
});

export type AppRouter = typeof appRouter;
