/**
 * Authoritative initial CE/FF project-context seed.
 * Financial, capital-source, opportunity, ROI, cash-flow, and return fields are intentionally absent.
 */
export const initialInternalProjectSeed = [
  {
    projectName: "Cedarwood Flats",
    projectType: "Multifamily Residential Development",
    projectStatus: "planning" as const,
    developmentStage: "development" as const,
    knownProgramSummary: "280 residential units across five buildings with 56 units per building. CE development portfolio context for multifamily, modular, and industrialized construction planning.",
    programUnitCount: 280,
    programBuildingCount: 5,
    programUnitsPerBuilding: 56,
    factoryFoundationRelationship: "Contextual Factory Foundation relationship only: the project may later connect construction estimating, manufacturing production, LGS wall panels, modular component flow, logistics, and installation. No operational system link is configured.",
    factoryFoundationRelationshipState: "contextual" as const,
    description: "CE residential multifamily demonstration project for repeatable, scalable housing using industrialized and modular construction. Building-level structure may later support capital needs, construction costs, production requirements, logistics, schedule, and project economics by building or phase. Financial and capital information remains not yet defined.",
  },
  {
    projectName: "Garden Lofts",
    projectType: "Multifamily / Mid-Rise Residential Development",
    projectStatus: "planning" as const,
    developmentStage: "development" as const,
    knownProgramSummary: "250 residential units in a mid-rise multifamily configuration. CE development portfolio context for higher-density urban or infill-style housing.",
    programUnitCount: 250,
    factoryFoundationRelationship: "Contextual Factory Foundation relationship only: the project may later associate manufactured components, LGS assemblies, modular workflows, material movement, production scheduling, transportation, staging, and installation. No operational system link is configured.",
    factoryFoundationRelationshipState: "contextual" as const,
    description: "CE multifamily development intended to evaluate industrialized construction at scale. Future capital needs may describe site development, construction, structural systems, framing, MEP, finishes, manufactured assemblies, logistics, equipment, professional services, financing, contingency, and working capital only when validated data is available.",
  },
  {
    projectName: "Stonepine Residences",
    projectType: "Single-Family Residential Development / Subdivision",
    projectStatus: "planning" as const,
    developmentStage: "development" as const,
    knownProgramSummary: "300 residential units in a single-family subdivision and residential community. Repeatable and standardized construction context.",
    programUnitCount: 300,
    factoryFoundationRelationship: "Contextual Factory Foundation relationship only: the project may later connect standardized home designs, LGS material flow, framing, panel production, transportation, staging, and installation. No operational system link is configured.",
    factoryFoundationRelationshipState: "contextual" as const,
    description: "CE scalable residential production project that may later be decomposed into phases, lots, homes, infrastructure, and common project requirements. Unknown land costs, construction costs, selling prices, financing, revenue, profit, ROI, and IRR remain not yet defined.",
  },
  {
    projectName: "Skyline Towers",
    projectType: "High-Rise Mixed-Use Development",
    projectStatus: "planning" as const,
    developmentStage: "development" as const,
    knownProgramSummary: "450 residential units within a high-rise mixed commercial/residential development and high-density urban project context.",
    programUnitCount: 450,
    factoryFoundationRelationship: "Contextual Factory Foundation relationship only: the project may later associate manufactured components, LGS systems where applicable, assemblies, logistics, staging, transportation, and installation. No operational system link is configured.",
    factoryFoundationRelationshipState: "contextual" as const,
    description: "CE high-density urban development for evaluating industrialized construction, manufactured components, automation, logistics, and project controls at a larger scale. Building height, commercial square footage, unit mix, cost, revenue, capital structure, and returns are not yet defined.",
  },
  {
    projectName: "Chappell International Manufacturing Facility",
    projectType: "Manufacturing / Industrial Facility",
    location: "Saginaw, Texas",
    projectStatus: "planning" as const,
    developmentStage: "development" as const,
    knownProgramSummary: "Approximately 100,000 square-foot manufacturing and development facility for LGS construction, modular construction, robotics, automation, material handling, fabrication, assembly, staging, and logistics. Concept includes manufacturing cells, east-side module staging, a gantry crane concept, west-side parking, southern access, and northern Phase 2 expansion context.",
    programAreaSqFt: 100000,
    programFootprintDescription: "Approximate conceptual footprint: 500 feet north-to-south by 300 feet east-to-west; long rectangular industrial building, subject to future design development and validation.",
    factoryFoundationRelationship: "Contextual Factory Foundation relationship only: planned physical manufacturing context for the Factory Foundation digital twin and related manufacturing, robotics, logistics, inventory, construction, scheduling, and analytics capabilities. No operational system link is configured.",
    factoryFoundationRelationshipState: "contextual" as const,
    description: "Planned CE manufacturing and development facility serving as the industrial backbone for industrialized construction. Potential future capital needs may include land, site development, building construction, production equipment, robotics, material handling, cranes, fabrication, automation, technology infrastructure, working capital, and expansion capital only when validated. Facility cost, ownership, financing, capacity, revenue, valuation, and return are not yet defined.",
  },
  {
    projectName: "Garden Haven",
    projectType: "Single-Family Residential Development",
    projectStatus: "planning" as const,
    developmentStage: "development" as const,
    knownProgramSummary: "100 residential units in a single-family residential development and repeatable residential production model with a potential industrialized and modular construction application.",
    programUnitCount: 100,
    factoryFoundationRelationship: "Contextual Factory Foundation relationship only: the project may later connect LGS components, wall panels, assemblies, material flow, transportation, staging, and installation. No operational system link is configured.",
    factoryFoundationRelationshipState: "contextual" as const,
    description: "CE single-family development for testing standardized home production, repeatable construction, material procurement, manufacturing integration, logistics, site development, schedule, and project economics. Project cost, land cost, selling price, financing, revenue, capital, profit, ROI, and IRR are not yet defined.",
  },
] as const;

export const internalProjectSeedExcludedFinancialFields = [
  "totalProjectCost",
  "capitalRequirement",
  "ROI / Returns model",
  "capital opportunities",
  "capital commitments",
  "awards",
  "cash flows",
  "returns",
] as const;
