import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cedarwoodHistoricalControlTotal, cedarwoodHistoricalControls } from "../../../shared/cedarwoodHistoricalPlanning";
import { formatCapitalAmount } from "../../../shared/capitalFormation";

const categoryLabel = (category: string) => ({ land_acquisition: "Land / acquisition", site_development: "Site development", building_modular: "Building / modular construction", factory_logistics_installation: "Factory / logistics / installation", professional_soft_costs: "Professional / soft costs", financing_carry: "Financing / carry", contingency: "Contingency" }[category] ?? category.replaceAll("_", " "));

export function CedarwoodHistoricalProForma({ summary, scenarioId, refresh }: any) {
  const [wbsExpanded, setWbsExpanded] = useState(false);
  const sensitivity = [
    ["$155 / SF", cedarwoodHistoricalControls.grossSfLow],
    ["$160 / SF", cedarwoodHistoricalControls.grossSfCentral],
    ["$165 / SF", cedarwoodHistoricalControls.grossSfHigh],
  ];
  const isReconciled = summary?.lineCount === 100 && summary?.total === cedarwoodHistoricalControlTotal;
  return <div className="cedarwood-proforma-workspace">
    <Card><CardHeader><div className="table-head"><div><div className="kicker">CEDARWOOD FLATS · REVERSE-ENGINEERED HISTORICAL PLANNING</div><CardTitle>$40M control total, translated into a governed project reference model</CardTitle></div><span className="roi-state estimated">estimated · effective date unknown</span></div></CardHeader><CardContent><p className="section-subtitle">This is the Cedarwood pilot: a user-authorized historical planning scenario, not a current budget, actual spend ledger, validated bid set, committed capital plan, or return forecast. Every WBS allocation is a reverse-engineered planning allowance that can later be replaced by dated source material.</p></CardContent></Card>
    <div className="internal-project-stats cedarwood-control-metrics"><div><span>CONTROL TOTAL</span><b>{formatCapitalAmount(cedarwoodHistoricalControls.totalDevelopmentCost)}</b><small>Historical planning basis</small></div><div><span>PROGRAM</span><b>{cedarwoodHistoricalControls.units} units</b><small>{cedarwoodHistoricalControls.buildings} buildings · {cedarwoodHistoricalControls.unitsPerBuilding} units / building</small></div><div><span>AREA</span><b>{cedarwoodHistoricalControls.grossSfCentral.toLocaleString()} SF</b><small>{cedarwoodHistoricalControls.averageSfPerUnit} SF / unit · derived</small></div><div><span>HISTORICAL NOI</span><b>{formatCapitalAmount(cedarwoodHistoricalControls.historicalNoi)}</b><small>Yield on cost: 11.875% · historical context only</small></div></div>
    <div className="cedarwood-proforma-grid"><Card><CardHeader><div className="kicker">COST-BASIS SENSITIVITY</div><CardTitle>Area implied by the historical planning range</CardTitle></CardHeader><CardContent><div className="cedarwood-sensitivity">{sensitivity.map(([basis, area]) => <div key={String(basis)} className={basis === "$160 / SF" ? "central" : ""}><b>{basis}</b><span>{Number(area).toLocaleString()} gross SF</span><small>{basis === "$160 / SF" ? "Central planning case" : "Historical sensitivity"}</small></div>)}</div><p className="section-subtitle">The $40M control total divided by the $160/SF central basis yields 250,000 gross SF. Module reference: {cedarwoodHistoricalControls.moduleEquivalents} 12' × 30' gross-area module equivalents, not confirmed physical module count.</p></CardContent></Card><Card><CardHeader><div className="kicker">RECONCILIATION</div><CardTitle>100-point WBS status</CardTitle></CardHeader><CardContent><div className="cedarwood-reconciliation"><b>{isReconciled ? "Reconciled" : "Awaiting WBS refresh"}</b><strong>{summary ? formatCapitalAmount(summary.total) : "Not loaded"}</strong><span>{summary?.lineCount ?? 0} of 100 historical planning lines</span><small>Target: {formatCapitalAmount(cedarwoodHistoricalControlTotal)} · no current capital need, monthly cash-flow, debt service, ROI, IRR, or payback result is created.</small></div>{scenarioId ? <Button variant="outline" disabled={refresh.isPending} onClick={() => refresh.mutate({ scenarioId })}>{refresh.isPending ? "Refreshing…" : "Refresh authorized WBS"}</Button> : null}</CardContent></Card></div>
    <Card><CardHeader><div className="kicker">REVERSE-ENGINEERED ALLOCATION</div><CardTitle>Budget categories reconcile to the historical control total</CardTitle></CardHeader><CardContent><div className="cedarwood-category-grid">{(summary?.byCategory ?? []).map((category: any) => <div key={category.costCategory}><span>{categoryLabel(category.costCategory)}</span><b>{formatCapitalAmount(category.amount)}</b><small>{category.lineCount} WBS lines · estimated</small></div>)}</div></CardContent></Card>
    <Card><CardHeader><div className="kicker">GOVERNED HANDOFFS</div><CardTitle>Connected where evidence exists; unavailable where timing or supporting terms are missing</CardTitle></CardHeader><CardContent><div className="cedarwood-handoff-grid"><div><span>INTERNAL PROJECT</span><b>Linked</b><small>Cedarwood Flats project context</small></div><div><span>CAPITAL NEEDS</span><b>Reference only</b><small>The $40M historical WBS does not create a current requirement</small></div><div><span>PROJECTIONS</span><b>Linked</b><small>Historical planning scenario {scenarioId || "unavailable"}</small></div><div><span>CASH FLOW / RETURNS</span><b>Unavailable</b><small>No monthly timing, revenue/expense split, or debt terms</small></div></div></CardContent></Card>
    <Card><CardHeader><div className="table-head"><div><div className="kicker">100-POINT WBS · HISTORICAL PLANNING</div><CardTitle>Source-labeled planning allowances, ready for progressive replacement</CardTitle></div><span className="roi-state estimated">reverse-engineered</span></div></CardHeader><CardContent>{summary?.lines?.length ? <><div className="cedarwood-work-surface-summary"><div><span>WBS LINES</span><b>{summary.lineCount} / 100</b></div><div><span>CONTROL TOTAL</span><b>{formatCapitalAmount(summary.total)}</b></div><div><span>STATE</span><b>Historical planning</b></div><Button variant="outline" aria-expanded={wbsExpanded} onClick={() => setWbsExpanded((expanded) => !expanded)}>{wbsExpanded ? "Collapse WBS ledger" : "Expand 100-line WBS ledger"}</Button></div>{wbsExpanded ? <div className="cedarwood-wbs-table"><div className="cedarwood-wbs-row head"><span>WBS</span><span>Description</span><span>Category / phase</span><span>Applicability</span><span>Allocation</span></div>{summary.lines.map((line: any) => <div key={line.id} className="cedarwood-wbs-row"><b>{line.wbsCode}</b><span>{line.description}<small>{line.sourceClassification.replaceAll("_", " ")} · source date unknown</small></span><span>{categoryLabel(line.costCategory)}<small>{line.phase.replaceAll("_", " ")}</small></span><span>{line.buildingApplicability}</span><strong>{formatCapitalAmount(line.allocatedAmount)}</strong></div>)}</div> : <div className="cedarwood-collapsed-note">The full 100-line planning ledger is collapsed. Category allocation, reconciliation, and historical-planning controls remain visible above.</div>}</> : <div className="empty-state">The authorized Cedarwood WBS has not been loaded. Use the refresh action after the historical planning scenario is available.</div>}</CardContent></Card>
    <div className="internal-projects-rule"><div className="kicker">MODEL BOUNDARY</div><b>WBS → Internal Project context and historical planning scenario. Not yet → current capital need, cash-flow schedule, debt service, return, or funding commitment.</b><p>Next replacement inputs are dated land/site cost, GMP or trade bids, rent and lease-up assumptions, operating-cost assumptions, construction schedule, and financing terms. Each replaces only the corresponding planning allowance after source review.</p></div>
  </div>;
}
